### ISSUE TITLE
Feature Request: multiple saves/in game load menu

### ISSUE THREAD

**Issue by yikies** [KingEnderBrine/-RoR2-ProperSave#23]
I would love to be able to have multiple saves since I don't often have time to do long runs anymore because of life. When I do get the chance to resume a longer run, I would often like to start a different run with a different character but don't want to lose my good run progress. It would be sweet to have a little menu that pops up that has a list of all my in progress runs and shows the character I was playing, stage number, and run time. For multiplayer, it could also show a quick list of other player names/character icons. Lastly, could have a load and delete button on the bottom for once you've selected a run. I know a lot of these features are a long shot but I figured I'd put in a request anyway, it's been something I've been thinking about for a while, thank you for your time!

**Comment by KingEnderBrine** [comment]
Hello, thanks for your request, but I won't do it. That makes no sense since there are unlockables that will not be available in saved games. And I don't like the idea of multiple saves in rogue-like games. None of the other rogue-like games I know do multiple save, it's always only a continue button.
