### ISSUE TITLE
Change MMHook Mod

### ISSUE THREAD

**Issue by NutNutty64** [KingEnderBrine/-RoR2-ProperSave#32]
It seems clear now that [HookGenPatcher](https://thunderstore.io/package/RiskofThunder/HookGenPatcher/) by RiskofThunder is the definitive mod for loading the MMHook assembly (R2API itself requires it now), and I suggest switching over to it to avoid issues and to make it so that people using the r2modman don't have two mods for loading the assembly.

**Comment by KingEnderBrine** [comment]
I will not do that just yet, because having both `HookGenPatcher` and `MMHOOK_Standalone` doesn't cause any issues, and I have something else in mind to do.

**Comment by Kyllingene** [comment]
`MMHOOK_Standalone` is now deprecated, and has no actual functionality (the downloads no longer contain a DLL); I'm not sure what your life is like right now, but if you have the time, it would be really nice to have an update.

**Comment by KingEnderBrine** [comment]
It didn't have dll for a long time, it just served as dependency to `HookGenPatcher`, which was not a problem, because everyone nowadays use r2modman/tmm which download all dependencies. Deprecation of `MMHOOK_Standalone` doesn't mean it's the reason why `ProperSave` doesn't work. The actual reason is that there are a lot of internal changes with DLC update.
I will update it, just wait.

**Comment by KingEnderBrine** [comment]
Published an update
