### ISSUE TITLE
Proper key names in save file

### ISSUE THREAD

**Issue by DrChristophFH** [KingEnderBrine/-RoR2-ProperSave#71]
Is it intentional that the keys in the safe file are all pretty much useless without looking at the code constantly to see what the configured serialization names are?

Having proper names would allow people who are not experienced with code to also tinker with their save files, or is this actively discouraged and hence the obfuscation? One could even explain in the readme or somewhere else what some of the values mean and influence.

**Comment by KingEnderBrine** [comment]
While obfuscation wasn't the intention, I won't change it and don't approve of save editing. The actual reason was file size, in case you had a lot of different items it was 5-10 times the difference.
You still need to be experienced user to change some parts of the file even if it had full names specified, because some things need runtime information to be read correctly like item indices.
